// App.tsx

import React, { useState, useEffect, useMemo } from 'react';
import { Plus, LayoutDashboard, ListTodo, PieChart, Settings as SettingsIcon } from 'lucide-react';
import { ExpiryItem, Category, AppSettings } from './types';
import Dashboard from './components/Dashboard';
import ExpiryItemCard from './components/ExpiryItemCard';
import AddEditModal from './components/AddEditModal';
import Summary from './components/Summary';
import Settings from './components/Settings';

const App: React.FC = () => {
  const [items, setItems] = useState<ExpiryItem[]>([]);
  const [settings, setSettings] = useState<AppSettings>({
    defaultReminderTime: '09:00',
    defaultReminderDays: 3,
    currency: 'TWD'
  });
  
  const [activeTab, setActiveTab] = useState<'dashboard' | 'list' | 'summary' | 'settings'>('dashboard');
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingItem, setEditingItem] = useState<ExpiryItem | undefined>(undefined);
  const [selectedCategory, setSelectedCategory] = useState<Category | 'all'>('all');

  // Persistence
  useEffect(() => {
    const savedItems = localStorage.getItem('expiry_butler_items');
    const savedSettings = localStorage.getItem('expiry_butler_settings');
    if (savedItems) setItems(JSON.parse(savedItems));
    if (savedSettings) setSettings(JSON.parse(savedSettings));
  }, []);

  useEffect(() => {
    localStorage.setItem('expiry_butler_items', JSON.stringify(items));
    localStorage.setItem('expiry_butler_settings', JSON.stringify(settings));
  }, [items, settings]);

  const filteredItems = useMemo(() => {
    return items.filter(item => {
      return selectedCategory === 'all' || item.category === selectedCategory;
    }).sort((a, b) => new Date(a.expiryDate).getTime() - new Date(b.expiryDate).getTime());
  }, [items, selectedCategory]);

  const handleSaveItem = (data: Partial<ExpiryItem>) => {
    if (editingItem) {
      setItems(items.map(i => i.id === editingItem.id ? { ...i, ...data } as ExpiryItem : i));
    } else {
      const newItem: ExpiryItem = {
        id: Math.random().toString(36).substr(2, 9),
        name: data.name!,
        category: data.category!,
        expiryDate: data.expiryDate!,
        reminderDays: data.reminderDays!,
        amount: data.amount,
        cycle: data.cycle,
        purchaseDate: data.purchaseDate,
        createdAt: new Date().toISOString()
      };
      setItems([...items, newItem]);
    }
    setIsModalOpen(false);
    setEditingItem(undefined);
  };

  const handleDeleteItem = (id: string) => {
    if (confirm('確定刪除？')) setItems(items.filter(i => i.id !== id));
  };

  const renderContent = () => {
    switch (activeTab) {
      case 'dashboard': return <Dashboard items={items} />;
      case 'summary': return <Summary items={items} />;
      case 'settings': return <Settings items={items} setItems={setItems} settings={settings} setSettings={setSettings} />;
      case 'list': return (
        <div className="space-y-4 animate-fadeIn">
            <div className="flex gap-2 overflow-x-auto pb-2 -mx-1 px-1 no-scrollbar">
                <button 
                  onClick={() => setSelectedCategory('all')}
                  className={`px-5 py-2 rounded-2xl text-xs font-black transition-all ${
                    selectedCategory === 'all' ? 'bg-slate-900 text-white shadow-lg' : 'bg-white text-slate-500 border border-slate-100'
                  }`}
                >
                  全部
                </button>
                {Object.values(Category).map(cat => (
                  <button 
                    key={cat}
                    onClick={() => setSelectedCategory(cat)}
                    className={`px-5 py-2 rounded-2xl text-xs font-black flex-shrink-0 transition-all ${
                      selectedCategory === cat ? 'bg-slate-900 text-white shadow-lg' : 'bg-white text-slate-500 border border-slate-100'
                    }`}
                  >
                    {cat}
                  </button>
                ))}
            </div>
            <div className="space-y-1">
                {filteredItems.map(item => (
                    <ExpiryItemCard key={item.id} item={item} onDelete={handleDeleteItem} onEdit={(i) => { setEditingItem(i); setIsModalOpen(true); }} />
                ))}
                {filteredItems.length === 0 && <div className="text-center py-20 text-slate-300 font-bold">空空如也</div>}
            </div>
        </div>
      );
    }
  };

  return (
    <div className="max-w-xl mx-auto min-h-screen flex flex-col bg-[#F9FAFB]">
      <header className="px-8 py-6 flex justify-between items-end">
        <div>
          <p className="text-[10px] font-black text-indigo-600 uppercase tracking-[0.2em] mb-1">Expiry Butler</p>
          <h1 className="text-3xl font-black text-slate-900 tracking-tighter">
            {activeTab === 'dashboard' ? '智慧管家' : activeTab === 'list' ? '提醒清單' : activeTab === 'summary' ? '財務彙總' : '系統設定'}
          </h1>
        </div>
        <div className="w-12 h-12 bg-white rounded-2xl shadow-sm border border-slate-100 flex items-center justify-center text-slate-400">
            <LayoutDashboard size={20} />
        </div>
      </header>

      <main className="flex-grow px-6 pb-28">
        {renderContent()}
      </main>

      <button 
        onClick={() => { setEditingItem(undefined); setIsModalOpen(true); }}
        className="fixed bottom-24 right-8 w-16 h-16 bg-slate-900 text-white rounded-[24px] shadow-2xl flex items-center justify-center active:scale-90 transition-all z-40"
      >
        <Plus size={32} />
      </button>

      <nav className="fixed bottom-0 left-0 right-0 max-w-xl mx-auto bg-white/95 backdrop-blur-xl border-t border-slate-100 flex justify-around items-center py-4 px-8 safe-bottom z-50 rounded-t-[40px] shadow-[0_-10px_40px_rgba(0,0,0,0.02)]">
        {[
            { id: 'dashboard', icon: LayoutDashboard, label: '概覽' },
            { id: 'list', icon: ListTodo, label: '清單' },
            { id: 'summary', icon: PieChart, label: '財務' },
            { id: 'settings', icon: SettingsIcon, label: '設定' }
        ].map(tab => (
            <button 
                key={tab.id}
                onClick={() => setActiveTab(tab.id as any)}
                className={`flex flex-col items-center gap-1.5 transition-all ${activeTab === tab.id ? 'text-indigo-600 scale-110' : 'text-slate-400 opacity-60'}`}
            >
                <tab.icon size={22} strokeWidth={activeTab === tab.id ? 3 : 2} />
                <span className="text-[9px] font-black uppercase tracking-widest">{tab.label}</span>
            </button>
        ))}
      </nav>

      <AddEditModal isOpen={isModalOpen} item={editingItem} onClose={() => { setIsModalOpen(false); setEditingItem(undefined); }} onSave={handleSaveItem} />

      <style>{`
        .no-scrollbar::-webkit-scrollbar { display: none; }
        .animate-fadeIn { animation: fadeIn 0.4s cubic-bezier(0.16, 1, 0.3, 1); }
        .animate-slideUp { animation: slideUp 0.4s cubic-bezier(0.16, 1, 0.3, 1); }
        @keyframes fadeIn { from { opacity: 0; transform: translateY(5px); } to { opacity: 1; transform: translateY(0); } }
        @keyframes slideUp { from { transform: translateY(100%); } to { transform: translateY(0); } }
        body { color: #1e293b; }
      `}</style>
    </div>
  );
};

export default App;

// src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ExpiryItem, Category, AppSettings } from './types';
import { DataService } from './services/data.service';
import { DashboardComponent } from './components/dashboard.component';
import { AddEditModalComponent } from './components/add-edit-modal.component';
import { ExpiryItemCardComponent } from './components/expiry-item-card.component';
import { SummaryComponent } from './components/summary.component';
import { SettingsComponent } from './components/settings.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    CommonModule,
    DashboardComponent,
    AddEditModalComponent,
    ExpiryItemCardComponent,
    SummaryComponent,
    SettingsComponent
  ],
  template: `
    <div class="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100">
      <!-- Header -->
      <div class="sticky top-0 z-40 bg-white border-b border-slate-100 backdrop-blur-md bg-white/80">
        <div class="max-w-2xl mx-auto px-6 py-4 flex justify-between items-center">
          <h1 class="text-2xl font-black text-slate-900 tracking-tight">Expiry Butler</h1>
          <button
            (click)="isModalOpen = true"
            class="p-3 bg-indigo-600 text-white rounded-full shadow-lg shadow-indigo-200 active:scale-90 transition-all text-xl"
          >
            +
          </button>
        </div>
      </div>

      <!-- Content -->
      <div class="max-w-2xl mx-auto p-6 pb-24">
        <!-- Dashboard Tab -->
        <div *ngIf="activeTab === 'dashboard'">
          <app-dashboard [items]="items"></app-dashboard>
        </div>

        <!-- List Tab -->
        <div *ngIf="activeTab === 'list'" class="space-y-4 animate-fadeIn">
          <div class="flex gap-2 overflow-x-auto pb-2 -mx-1 px-1 no-scrollbar">
            <button
              (click)="selectedCategory = 'all'"
              [ngClass]="{
                'bg-slate-900 text-white shadow-lg': selectedCategory === 'all',
                'bg-white text-slate-500 border border-slate-100': selectedCategory !== 'all'
              }"
              class="px-5 py-2 rounded-2xl text-xs font-black transition-all"
            >
              全部
            </button>
            <button
              *ngFor="let cat of categories"
              (click)="selectedCategory = cat"
              [ngClass]="{
                'bg-slate-900 text-white shadow-lg': selectedCategory === cat,
                'bg-white text-slate-500 border border-slate-100': selectedCategory !== cat
              }"
              class="px-5 py-2 rounded-2xl text-xs font-black flex-shrink-0 transition-all"
            >
              {{ cat }}
            </button>
          </div>

          <div class="space-y-1">
            <app-expiry-item-card
              *ngFor="let item of filteredItems"
              [item]="item"
              (onEdit)="handleEditItem($event)"
              (onDelete)="handleDeleteItem($event)"
            ></app-expiry-item-card>
            <div *ngIf="filteredItems.length === 0" class="text-center py-20 text-slate-300 font-bold">
              空空如也
            </div>
          </div>
        </div>

        <!-- Summary Tab -->
        <div *ngIf="activeTab === 'summary'">
          <app-summary [items]="items"></app-summary>
        </div>

        <!-- Settings Tab -->
        <div *ngIf="activeTab === 'settings'">
          <app-settings
            [settings]="settings"
            [items]="items"
            (settingsChange)="handleSettingsChange($event)"
            (itemsChange)="handleItemsChange($event)"
          ></app-settings>
        </div>
      </div>

      <!-- Bottom Navigation -->
      <div class="fixed bottom-0 left-0 right-0 bg-white border-t border-slate-100 backdrop-blur-md bg-white/80">
        <div class="max-w-2xl mx-auto px-6 py-3 flex justify-around">
          <button
            (click)="activeTab = 'dashboard'"
            [ngClass]="{ 'text-indigo-600': activeTab === 'dashboard', 'text-slate-400': activeTab !== 'dashboard' }"
            class="flex flex-col items-center gap-1 p-3 rounded-2xl transition-all text-lg"
          >
            <span>📊</span>
            <span class="text-[10px] font-bold">儀表板</span>
          </button>
          <button
            (click)="activeTab = 'list'"
            [ngClass]="{ 'text-indigo-600': activeTab === 'list', 'text-slate-400': activeTab !== 'list' }"
            class="flex flex-col items-center gap-1 p-3 rounded-2xl transition-all text-lg"
          >
            <span>📋</span>
            <span class="text-[10px] font-bold">列表</span>
          </button>
          <button
            (click)="activeTab = 'summary'"
            [ngClass]="{ 'text-indigo-600': activeTab === 'summary', 'text-slate-400': activeTab !== 'summary' }"
            class="flex flex-col items-center gap-1 p-3 rounded-2xl transition-all text-lg"
          >
            <span>📈</span>
            <span class="text-[10px] font-bold">統計</span>
          </button>
          <button
            (click)="activeTab = 'settings'"
            [ngClass]="{ 'text-indigo-600': activeTab === 'settings', 'text-slate-400': activeTab !== 'settings' }"
            class="flex flex-col items-center gap-1 p-3 rounded-2xl transition-all text-lg"
          >
            <span>⚙</span>
            <span class="text-[10px] font-bold">設定</span>
          </button>
        </div>
      </div>

      <!-- Modal -->
      <app-add-edit-modal
        [item]="editingItem"
        [isOpen]="isModalOpen"
        (onClose)="handleModalClose()"
        (onSave)="handleSaveItem($event)"
      ></app-add-edit-modal>
    </div>
  `,
  styles: [`
    :host {
      display: block;
    }
  `]
})
export class AppComponent implements OnInit {
  activeTab: 'dashboard' | 'list' | 'summary' | 'settings' = 'dashboard';
  isModalOpen = false;
  editingItem: ExpiryItem | undefined;
  selectedCategory: Category | 'all' = 'all';

  items: ExpiryItem[] = [];
  settings: AppSettings = {
    defaultReminderTime: '09:00',
    defaultReminderDays: 3,
    currency: 'TWD'
  };

  categories = Object.values(Category);

  get filteredItems(): ExpiryItem[] {
    let filtered = this.items;

    if (this.selectedCategory !== 'all') {
      filtered = filtered.filter(item => item.category === this.selectedCategory);
    }

    return filtered.sort((a, b) => new Date(a.expiryDate).getTime() - new Date(b.expiryDate).getTime());
  }

  constructor(private dataService: DataService) {}

  ngOnInit(): void {
    this.dataService.items$.subscribe(items => {
      this.items = items;
    });

    this.dataService.settings$.subscribe(settings => {
      this.settings = settings;
    });
  }

  handleSaveItem(data: Partial<ExpiryItem>): void {
    if (this.editingItem) {
      this.dataService.updateItem(this.editingItem.id, data);
    } else {
      this.dataService.addItem(data);
    }
    this.isModalOpen = false;
    this.editingItem = undefined;
  }

  handleDeleteItem(id: string): void {
    if (confirm('確定刪除？')) {
      this.dataService.deleteItem(id);
    }
  }

  handleEditItem(item: ExpiryItem): void {
    this.editingItem = item;
    this.isModalOpen = true;
  }

  handleModalClose(): void {
    this.isModalOpen = false;
    this.editingItem = undefined;
  }

  handleSettingsChange(settings: AppSettings): void {
    this.dataService.updateSettings(settings);
  }

  handleItemsChange(items: ExpiryItem[]): void {
    this.dataService.importData({
      items,
      settings: this.settings
    });
  }
}

<div class="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100">
  <!-- Header -->
  <div class="sticky top-0 z-40 bg-white border-b border-slate-100 backdrop-blur-md bg-white/80">
    <div class="max-w-2xl mx-auto px-6 py-4 flex justify-between items-center">
      <h1 class="text-2xl font-black text-slate-900 tracking-tight">Expiry Butler</h1>
      <button
        (click)="isModalOpen = true"
        class="p-3 bg-indigo-600 text-white rounded-full shadow-lg shadow-indigo-200 active:scale-90 transition-all text-xl"
      >
        +
      </button>
    </div>
  </div>

  <!-- Content -->
  <div class="max-w-2xl mx-auto p-6 pb-24">
    <!-- Dashboard Tab -->
    <div *ngIf="activeTab === 'dashboard'">
      <app-dashboard [items]="items"></app-dashboard>
    </div>

    <!-- List Tab -->
    <div *ngIf="activeTab === 'list'" class="space-y-4 animate-fadeIn">
      <div class="flex gap-2 overflow-x-auto pb-2 -mx-1 px-1 no-scrollbar">
        <button
          (click)="selectedCategory = 'all'"
          [ngClass]="{
            'bg-slate-900 text-white shadow-lg': selectedCategory === 'all',
            'bg-white text-slate-500 border border-slate-100': selectedCategory !== 'all'
          }"
          class="px-5 py-2 rounded-2xl text-xs font-black transition-all"
        >
          全部
        </button>
        <button
          *ngFor="let cat of categories"
          (click)="selectedCategory = cat"
          [ngClass]="{
            'bg-slate-900 text-white shadow-lg': selectedCategory === cat,
            'bg-white text-slate-500 border border-slate-100': selectedCategory !== cat
          }"
          class="px-5 py-2 rounded-2xl text-xs font-black flex-shrink-0 transition-all"
        >
          {{ cat }}
        </button>
      </div>

      <div class="space-y-1">
        <app-expiry-item-card
          *ngFor="let item of filteredItems"
          [item]="item"
          (onEdit)="handleEditItem($event)"
          (onDelete)="handleDeleteItem($event)"
        ></app-expiry-item-card>
        <div *ngIf="filteredItems.length === 0" class="text-center py-20 text-slate-300 font-bold">
          空空如也
        </div>
      </div>
    </div>

    <!-- Summary Tab -->
    <div *ngIf="activeTab === 'summary'">
      <app-summary [items]="items"></app-summary>
    </div>

    <!-- Settings Tab -->
    <div *ngIf="activeTab === 'settings'">
      <app-settings
        [settings]="settings"
        [items]="items"
        (settingsChange)="handleSettingsChange($event)"
        (itemsChange)="handleItemsChange($event)"
      ></app-settings>
    </div>
  </div>

  <!-- Bottom Navigation -->
  <div class="fixed bottom-0 left-0 right-0 bg-white border-t border-slate-100 backdrop-blur-md bg-white/80">
    <div class="max-w-2xl mx-auto px-6 py-3 flex justify-around">
      <button
        (click)="activeTab = 'dashboard'"
        [ngClass]="{ 'text-indigo-600': activeTab === 'dashboard', 'text-slate-400': activeTab !== 'dashboard' }"
        class="flex flex-col items-center gap-1 p-3 rounded-2xl transition-all text-lg"
      >
        <span>📊</span>
        <span class="text-[10px] font-bold">儀表板</span>
      </button>
      <button
        (click)="activeTab = 'list'"
        [ngClass]="{ 'text-indigo-600': activeTab === 'list', 'text-slate-400': activeTab !== 'list' }"
        class="flex flex-col items-center gap-1 p-3 rounded-2xl transition-all text-lg"
      >
        <span>📋</span>
        <span class="text-[10px] font-bold">列表</span>
      </button>
      <button
        (click)="activeTab = 'summary'"
        [ngClass]="{ 'text-indigo-600': activeTab === 'summary', 'text-slate-400': activeTab !== 'summary' }"
        class="flex flex-col items-center gap-1 p-3 rounded-2xl transition-all text-lg"
      >
        <span>📈</span>
        <span class="text-[10px] font-bold">統計</span>
      </button>
      <button
        (click)="activeTab = 'settings'"
        [ngClass]="{ 'text-indigo-600': activeTab === 'settings', 'text-slate-400': activeTab !== 'settings' }"
        class="flex flex-col items-center gap-1 p-3 rounded-2xl transition-all text-lg"
      >
        <span>⚙</span>
        <span class="text-[10px] font-bold">設定</span>
      </button>
    </div>
  </div>

  <!-- Modal -->
  <app-add-edit-modal
    [item]="editingItem"
    [isOpen]="isModalOpen"
    (onClose)="handleModalClose()"
    (onSave)="handleSaveItem($event)"
  ></app-add-edit-modal>
</div>
